# Jekyll 설정 파일
title: 한국전기절감원(주)
description: 지속가능한 친환경·저탄소 산업생태계 구축을 위한 전력절감 솔루션
url: "https://aporee.github.io"
baseurl: ""

# 빌드 설정
markdown: kramdown
highlighter: rouge
permalink: pretty

# 플러그인
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 데이터 파일 경로
data_dir: _data

# 기본 레이아웃
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# 제외할 파일/폴더
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
